FROM node:18 as development

WORKDIR /app

# Update package list and install the latest version of OpenSSL
RUN apt-get update && apt-get install -y openssl

COPY ./package*.json ./
RUN npm install

COPY . .

CMD ["npm", "start"]
