FROM node:18 as development

WORKDIR /app

# Update and install necessary packages
RUN apt-get update && apt-get upgrade -y && apt-get install -y openssl

COPY ./package*.json ./
RUN npm install

COPY . .

CMD ["npm", "start"]
